"Tengo la esperanza de que"
"Son pilares fundamentales para"
"Sea de una vez por todas realidad"
"Pero es evidente que estamos ante"
"Una llamada a la conciencia general"
"Gracias a la lucha de todos ustedes se ha logrado"
"Las actuaciones previstas van a suponer un gran impulso para"
"No podemos compartir que"
"Vamos a tratar en primer lugar de"
"Es un hecho significativo que "
"Participar activamente en"
"Han sido objeto de preocupación y atención prioritaria"
"Y con todo lo que ello conlleva"
"A la mayor brevedad posible"
"Algo tan sencillo como"
"Aportan su esfuerzo"
"Contribuye con una aportación sustantiva"
"Quiero formalmente trasladar nuestro apoyo a"
"Estar plenamente operativa dentro de unas semanas"
"Con un especial énfasis en"
"Valoramos muy positivamente que"
"Puntos que es necesario abordar"
"Estamos obligado a actuar con urgencia y con rigor"
"Está contribuyendo al sostenimiento de"
"Convenientemente informados"
"Siempre teniendo en cuenta que"
"Dar cumplimiento pleno a"
"Quiero agradecer nuevamente a todos los que están haciendo posible que"
"En ese sentido volvemos a plantear"
"Posición clara y contundente"
"Están adquiriendo una importancia creciente"
"Dar un respaldo incondicional a"
"Quiero asegurarles que hemos iniciado el camino de la recuperación"
"Constituye una gran prioridad"
"Ponerle énfasis en"
"Adoptación de nuevas medidas"
"Os debo confensar que"
"Me esforzar para lograrlo"
"Yo simplemente le invito a que.."
"Pronto vamos a poder valorar sus resultados"
"Incapaces de luchar adecuadamente contra"
"Sensación de indignación"
"Serio y riguroso"
"Sobre la bases de que"
"Se olvida de otro tema muy importante"
"Afectando de manera singular a"
"Solicitar el apoyo de"
"Carece absolutamente de sentido"
"Talante y serenidad"
"Estar a la altura de las necesidades de"
"Como no puede ser de otro modo"
"Para ello tienen que tener las condiciones adecuadas"
"Por consiguiente, creemos que es una medida inadecuada"
"Quiero dedicar una especial atención a"
"Destinada al desarrollo de"
"Se está convirtiendo rápidamente en el primer"
"Plantea la necesidad de que"
"Soy el primero que lo siente así"
"Hoy es un buen día para recordarlo"
"Es un valor esencial"
"Mayoritaria y determinante"
"Trabajar conjuntamente y a fondo en el tema de la seguridad por"
"Por todo lo anteriormente expuesto"
"Que ha permitido que"
"Tal como ha venido haciendo gala"
"Uno de sus máximos objetivos"
"Tendremos la oportunidad de asumir mayores responsabilidades"
"Puede y debe mejorar"
"Sus efectos ya no se limitan a"
"No tienen vuelta atrs"
"Otra de las cuestiones fundamentales"
"Pido que sea consecuente con"
"Forman parte de los esquemas operativos"
"Quiero hacer un reconocimiento a la muy importante labor de.."
"Eso en los prximos 12 meses debe corregirse"
"Que han caracterizado buena parte de la acción de"
"Eso nos lleva a recordar que"
"Puede resultar muy útil"
"Vamos a liderar este esfuerzo"
"Y os quiero decir algo que es tan importante como"
"Me sumo a los deseos expresados"
"Es una apuesta de futuro"
"Por poner ejemplos reales"
"Principalmente debido a"
"Intercambio de puntos de vista"
"La primera lnea de defensa de"
"Canalizar los recursos de forma uniforme"
"Esta labor se ver reforzada con"
"No saber lo que se trae entre manos"
"Impulsaremos un programa ambicioso"
"Siendo un eje de desarrollo"
"Pondrá todo su empeño en "
"Respuesta transparente y clara"
"No estar a la altura de las circunstancias"
"Ligado a una última reflexión"
"Tenemos en nuestras manos"
"Incrementar los medios destinados a"
"En ese terreno.."
"Procedimiento ágil y seguro"
"Puede corroborar que"
"Es la gran necesidad de nuestro tiempo"
"Estamos trabajando intensamente en"
"Que desde luego es el objeto que nos venimos marcando"
"Traslado el interés de mi departamento"
"Es una tarea de acometer con urgencia"
"Parte esencial de"
"Desde el punto de vista de"
"Apoyando un proyecto de especial importancia"
"En función de las condiciones"
"Sobradamente conocido"
"De naturaleza representativa"
"Haca usted referencia a"
"Graves problemas de"
"Avanza de forma sustancial en algunas materias"
"De manera irremediable"
"Por ello reitero que"
"Leal a sus ideas y a su tierra"
"Los datos ms recientes hacen predecir"
"Los principales retos que tuviramos que abordar de cara al futuro"
"Condicionantes negativos"
"Se requieren muy pocas explicaciones"
"Nuestro objetivo no es otro que trabajar por el desarrollo de"
"En función de las caractersticas de"
"Hoy ms que nunca"
"Y no le quepa ninguna duda de que"
"Eso lgicamente tiene que ver con"
"En las mismas condiciones que se vena desarrollando"
"Por su parte"
"Capaces de garantizar"
"Relación preferente con"
"Constituyen un reto imprescióndible"
"Desarrolla todos los aspectos relevantes"
"Adems de ello"
"Sobre esta materia"
"Eslabn multidireccional"
"Y lo que es ms importante"
"Debemos ser firmes en"
"Para cuyo desarrollo solicitaremos el apoyo de"
"Tendremos que seguir encarando situaciones adversas"
"Con los matices que fuese necesario"
"Hoy conocemos los resultados de"
"Nos debe conducir a reducir"
"Se van a concentrar los esfuerzos de"
"Reforzando la"
"Bsicamente con el mismo criterio"
"Son sin duda alguna muy significativos"
"Con una atención muy especfica a"
"En lnea con"
"Como saben"
"Para poder seguir avanzando en"
"Y por supuesto hemos actuado firmemente"
"No obstante, nos encontramos ante"
"Va siendo hora de que ustedes tengan posición sobre el tema"
"En torno a la necesidad de mejora de"
"Conocer de primera mano la dimensin de"
"Ha roto la barrera de"
"Todo ello trajo por consecuencia"
"Ha sido de una eficacia muy importante"
"Le voy a hacer alguna consideración al respecto"
"La realidad a la que nos referimos"
"Queda un gran tramo por recorrer"
"Se lo aseguro"
"Se ve reflejado en"
"Se ha encargado de llevar a cabo la"
"Llevar a la prctica los puntos anteriormente"
"No debiera de producirse"
"Las cosas se pueden lograr desde"
"Enfocadas u orientadas a"
"Se ha consolidado como"
"De manera constante y rigurosa"
"Ser sin duda alguna un gran revulsivo para lo que representa"
"Entre los pases participantes"
"Cuantitativamente y cualitativamente"
"Cuya tarea pasar a la historia por su"
"El objetivo es el mismo"
"La que mejor permite defender los intereses de"
"Proceso de convergencia"
"Con ese fin"
"El primer paso que vamos a adoptar"
"Priorizar el mximo esfuerzo en"
"Cuestin de cortesa"
"Vamos a estudiarlo con mucho gusto"
"Encima de cualquier inters poltico"
"Conforme al orden establecido"
"Tenemos el reto de incrementar la eficiencia"
"Estas son las lneas maestras de la acción de"
"Puso de manifiesto"
"En función de las diferentes caractersticas"
"Valiosas aportaciones"
"Estamos decididamente comprometidos con"
"Al que no nos vamos a sumar"
"El panorama es sombro"
"Principal rgano de coordinación"
"Pero tampoco es menos cierto que"
"Desbordado por los acontecimientos"
"Y tambin cada vez ms a"
"En virtud de un conjunto de normas"
"Como bien conoce"
"Yo creo que por lo tanto"
"Falta de capacidad de gestin"
"Estudiar el fondo de la cuestin"
"En la senda de"
"Todos los elementos que la implican"
"Pero s me gustara dejarle muy claro"
"Solución acertada"
"Quisiera destacar"
"Compartimos el mismo objetivo que ustedes"
"Tenemos dudas respecto a"
"Quiero expresar mi satisfacción por"
"Realizar un anlisis exhaustivo sobre"
"Dada la situación actual"
"Medidas que vayan en la dirección de"
"Entre las cuales destacan"
"Me alegra particularmente que"
"Con lo cual, en definitiva"
"Se ha diseado un paquete de medidas"
"Es especialmente relevante"
"Han sido objeto de atención prioritaria"
"Su actuación vendr marcada por"
"Deberamos matizar algun aspecto"
"Es una condición indispensable para"
"Lneas de acción que se han planteado"
"Medidas que irn acompaadas de"
"Instrumento que permite desarrollar"
"Hemos superado la prueba con creces"
"Nuestro principal reto es"
"Paso a continuación a hablarles de"
"Bsicamente, fundamentalmente"
"No deja de ser una contradicción en si misma"
"Lograr la mxima satisfacción posible"
"Para alcanzar estos objetivos vamos a llevar a cabo las siguientes medidas"
"Actuar con la misma coherencia"
"Hoy es ms necesario que nunca"
"De especial relevancia"
"Seguiremos poniendo en marcha medidas y planteando nuevos retos"
"Porque entendemos que esta es la nica forma de conseguir que"
"Quiero especialmente subrayar"
"Como bien saben ustedes"
"Con una importante aportación de"
"Obedece sin duda alguna a la labor de"
"Se ver sustancialmente incrementado"
"Quiero felicitarle por este compromiso"
"Pero quiero tranquilizarles porque"
"Slo cabe una conclusin"
"Finalmente, quisiera hacer una reflexin sobre"
"Ha querido destacar el empeo que ha sido puesto en"
"Debo resaltar que a partir de ahora"
"Es la mejor manera de que"
"Medidas que puedan permitir un mejor"
"Nunca lo hemos considerado prioritario"
"Uno de los objetivos fundamentales que nos planteamos"
"La meta la vamos a alcanzar"
"Por determinadas circunstancias ajenas a nuestra voluntad"
"Ofrecer mayores detalles sobre"
"El incremento registrado"
"En trminos globales"
"Tengo mucho que agradecerles"
"Su importancia se destaca por"
"Proponer futuras lneas de actuación"
"Hoy quiero asegurar que"
"Debemos considerar sus repercusiones"
"Su labor resulta de gran importancia"
"La triste realidad es que"
"Resulta evidente que"
"Quiero reiterarlo pblicamente"
"Desarrollar los instrumentos y herramientas para afrontar"
"Debido a la falta de entendimiento"
"Pero a la par, exigen la participación de"
"Mis primeras palabras van dirigidas a"
"Una vez establecidos los aspectos bsicos de"
"Estos son objetivos irrenunciables"
"Para abordar un reto de estas caractersticas necesitamos"
"Dificultades en todos los frentes"
"Obstculos en la lucha por"
"Recordarn ustedes que"
"En un proceso que ya no tiene retorno"
"Hemos padecido fuertes aumentos de"
"De una manera ms concreta"
"Para contrarrestar el efecto de"
"Otro aspecto relevante es"
"Que viene padeciendo desde hace mucho tiempo"
"Ha causado una especial expectación"
"A partir de esta constatación"
"Tenemos que desarrollar estas actividades sin afectar a"
"Expresar con claridad la voluntad de"
"Tenemos por delante el reto de"
"Debe garantizarse la seguridad de"
"Este es un factor esencial"
"Debemos desplegar un conjunto de acciones inmediatas"
"Lo mismo podramos decir de"
"Tiene amplia experiencia en"
"Yo no creo que sea lo ms apropiado"
"Supone un paso substancial en"
"Abordar en profundidad el problema"
"Es una misin digna y ejemplar"
"Hemos abordado otras cuestiones que ataen a"
"Lo que pone de relieve la singular importancia de"
"Y de manera muy especial"
"Y muy especialmente agradecer la presencia de"
"Tiene como principal objetivo que"
"Quiero por ello agradecerles a todos ustedes por"
"Anlisis serio de la realidad"
"Le da sostenibilidad en el tiempo"
"Quiero sumarme a"
"Se ha extendido prcticamente a"
"A ello aadir el compromiso de mantener el esfuerzo en"
"Extraordinaria contribución de"
"En torno a"
"Mantenemos viva la esperanza de"
"Establezcer las bases para"
"Creo necesario dejar constancia"
"En materia de"
"En este sentido"
"Ha sufrido cambios sustanciales"
"Ha hecho una gran labor"
"La primera cuestión que debemos abordar.."
"Despus de duras y complejas negociaciones"
"Hay dos cuestiones que deberan ser tratados con el máximo rigor"
"Y desde luego, lo que no vamos a hacer es"
"En definitiva"
"Diversas iniciativa en esa dirección"
"Se ha centrado especialmente en"
"Esa es la razn por la que"
"Tenemos el firme propósito de"
"Finalmente me referir a"
"Hoy anuncio ante ustedes"
"Es lacerante, intolerable, inasumible,.."
"No debera limitarse a"
"Someterlo a su consideración"
"Quiero en primer lugar agradecer el esfuerzo de"
"Pero s me gustara sealar que"
"Es ya una realidad"
"En modo alguno"
"Impulso de los ejes de acción"
"Posicionarnos de manera decidida en"
"Esa es la razn por la cual"
"Gracias especialmente por"
"Exige un esfuerzo contnuo"
"Estn contribuyendo a lograr"
"Elaborar un plan de acción contra"
"Debe representar tambin un reto"
"La antesala de un cambio sustancial"
"Se ha puesto en marcha el"
"Estamos hablando de un mbito de enorme trascendencia para"
"Ello tiene tambin una especial importancia"
"Todos aquellos aspectos que hacen referencia a"
"Como saben"
"Junto a todo esto"
"En el marco de"
"Tambin nos gustara conocer"
"En condiciones de efectividad"
"La conveniencia de"
"Dicho sea de paso"
"Reforzado"
"Especialmente deseo"
"Con la particularidad de que"
"Situarse en el entorno de"
"Son un claro ejemplo de ello"
"Soy bien consciente de la enorme dificultad que implica"
"Me gustara que ese fuera el principal mensaje"
"Abordar fundamentalmente el tema de"
"La realidad es bastante evidente"
"Como ya se anunció hace algunas semanas"
"Ha demostrado que la realidad no es esta"
"Las principales beneficiarias de esta medida"
"Aliado firme y comprometido"
"Trasciende las fronteras de"
"Quiero subrayar que"
"Por supuesto"
"Y espero que la historia pueda juzgarnos por haber.."
"Ante las nuevas amenazas"
"Acúten al dictado de sus intereses"
"Una política fundamental en este campo"
"Mejor manera de mostrar el grado de lealtad"
"Al que acabo de referirme"
"Desembocar lgicamente en"
"Tengo confianza plena en"
"Tantas veces como sea necesario"
"Pero ante todo quiero expresar"
"Son un parmetro indispensable para la toma de decisiones"
"De carácter urgente"
"Est inmersa en un proceso de renovación"
"Ante la difcil situación que vive"
"Conforme est establecido"
"Lo que s puedo asegurarle es que.."
"No es una mera afirmación"
"Procederemos a su aplicación y desarrollo"
"Se opone radicalmente contra este tipo de"
"En trminos estrictamente de.."
"Totalmente insostenible"
"Yo estoy de acuerdo con la lgica de"
"sta es la situación real a da de hoy"
"Que sin duda alguna posibilitar"
"Usted ha hecho referencia a"
"Las enormes dificultades que plantea"
